<?php 
require('include/config.php');
if(ReportError)
{
	ini_set('display_startup_errors',1);
	ini_set('display_errors',1);
	error_reporting(-1);
}
else
	error_reporting(0);
require('include/function.php');
require('.ht.php');
session::start();
__construct();
